baseURL = "https://USharma002.github.io/" # Replace with your actual base URL
title = "USharma Notes"
theme = ["PaperMod"]

enableRobotsTXT = true
enableEmoji = true
pygmentsUseClasses = true # Good for code highlighting if you use it
# mainsections = ["posts"] # Uncomment and adjust if you have specific main sections

[languages]
  [languages.en]
    languageName = "English"
    weight = 1
    # title = "USharma Notes" # Optional: Override global title for this language
    #[[languages.en.menu.main]]
    #  name = "Home"
    #  url = "/"
    #  weight = 1
    [[languages.en.menu.main]]
      name = "Posts"
      url = "/" # Assuming you have a 'posts' section
      weight = 5
    [[languages.en.menu.main]]
      name = "Tags"
      url = "/tags/"
      weight = 15
    [[languages.en.menu.main]]
      name = "Archive"
      url = "/archives/"
      weight = 15
    [[languages.en.menu.main]]
      name = "About"
      url = "/about/"
      weight = 20

[params]
  defaultTheme = "auto" # Options: "light", "dark", "auto"
  ShowReadingTime = true
  ShowShareButtons = false # Set to true if you want share buttons
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  paginate = 20
  ShowPageNums = true
  separator = true
  math = true

  comments = true

  [params.homeInfoParams]
    Title = "Welcome! 👋"
    Content = "This is an archive of my online notes on Computer Vision, Computer Graphics and Deep Learning!"
  
  [params.fuseOpts]
    isCaseSensitive = false
    shouldSort = true
    location = 0
    distance = 1000
    threshold = 0.3
    minMatchCharLength = 2
    keys = ["title", "permalink", "summary", "content"]
  
[outputs]
  home = ["HTML", "RSS", "JSON"] # JSON is good for search functionality in PaperMod
  
[markup]
  [markup.goldmark.renderer]
    unsafe = true # Usually needed for themes that allow raw HTML in markdown
  
  [markup.highlight]
    noClasses = false
    # style = "monokai" # Or any other Chroma style
  
  [markup.goldmark]
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['\[', '\]'], ['$$', '$$']]
          inline = [['\(', '\)']]